context("Confidence interval construction")
n = 30; p = 3
x = matrix(rnorm(n*p),n,p)
y = rnorm(n, x %*% rnorm(p), sd = 0.5)
beta = 2
yBin = rbinom(n, size = 1, prob = expit(x*beta))
R2objCV <- oosse(y = y, x = x, predFun = predFunTest, fitFun = fitFunTest, printTimeEstimate = FALSE)
Brierobj <- oosse(y = yBin, x = x, predFun = predFunBin, fitFun = fitFunBin, printTimeEstimate = FALSE, skillScore = "Brier")
Heidkeobj <- oosse(y = yBin, x = x, predFun = predFunBin, fitFun = fitFunBin, printTimeEstimate = FALSE, skillScore = "Heidke")
MSSobj <- oosse(y = yBin, x = x, predFun = predFunBin, fitFun = fitFunBin, printTimeEstimate = FALSE, skillScore = "Missclassification")
McFaddenobj <- oosse(y = yBin, x = x, predFun = predFunBin, fitFun = fitFunBin, printTimeEstimate = FALSE, skillScore = "McFadden")
test_that("confidence intervals are built with correct boundaries", {
    expect_silent(confIntR2 <- buildConfInt(R2objCV))
    expect_silent(confIntMSE <- buildConfInt(R2objCV, what = "MSE"))
    expect_silent(confIntMST <- buildConfInt(R2objCV, what = "MST", conf = 0.94))
    expect_true(all(confIntR2 <= 1))
    expect_true(all(confIntMSE >= 0))
    expect_true(all(confIntMST >= 0))
    expect_silent(confIntBrier <- buildConfInt(Brierobj))
    expect_silent(confIntModel <- buildConfInt(Brierobj, what = "BrierScore"))
    expect_silent(confIntRef <- buildConfInt(Brierobj, what = "ReferenceBrierScore", conf = 0.94))
    expect_true(all(confIntBrier <= 1))
    expect_true(all(confIntModel >= 0 & confIntModel <= 1))
    expect_true(all(confIntRef >= 0 & confIntRef <= 1))
    expect_silent(confIntHeidke <- buildConfInt(Heidkeobj))
    expect_silent(confIntModelHSS <- buildConfInt(Heidkeobj, what = "ModelMissclassRate"))
    expect_silent(confIntRefHSS <- buildConfInt(Heidkeobj, what = "ReferenceMissclassRate", conf = 0.94))
    expect_true(all(confIntHeidke <= 1))
    expect_true(all(confIntModelHSS >= 0 & confIntModelHSS <= 1))
    expect_true(all(confIntRefHSS >= 0 & confIntRefHSS <= 1))
    expect_silent(confIntMSS <- buildConfInt(MSSobj))
    expect_silent(confIntMcFadden <- buildConfInt(McFaddenobj))
    expect_true(all(confIntMSS <= 1))
    expect_true(all(confIntMcFadden <= 1))
    expect_silent(confIntRefMSS <- buildConfInt(MSSobj, what = "ReferenceMissclassRate", conf = 0.94))
    expect_silent(confIntRefMcFadden <- buildConfInt(McFaddenobj, what = "ReferenceLogLoss", conf = 0.94))
    expect_true(all(confIntModelHSS >= 0 & confIntModelHSS <= 1))
    expect_true(all(confIntRefMcFadden >= 0 & confIntRefMcFadden <= 1))
})
test_that("buildConfInt throws an error when incorrect input is provided", {
    expect_error(buildConfInt(R2objCV, what = "variance"))
    expect_error(buildConfInt(R2objCV, conf = 2))
    expect_error(buildConfInt(Heidkeobj, what = "MSE"))
    })
